% This is an autogenerated sample test for file rockPaperScissors
classdef testrockPaperScissors < matlab.unittest.TestCase
    methods (Test)
        function test_rockPaperScissors(testCase)
            % Specify the input(s) of rockPaperScissors
            p1 = "rock"
            p2 = "scissors"

            % Exercise the function rockPaperScissors
            actualOutput_result = rockPaperScissors(p1,p2)

            % Specify the expected output(s) of rockPaperScissors
            expectedOutput_result = "Player 1 wins"

            testCase.verifyEqual(actualOutput_result, expectedOutput_result);
        end
    end
end